### ISSUE TITLE
devdraw: X11 windows are not redrawn on resize events

### ISSUE THREAD

**Issue by jroimartin** [9fans/plan9port#339]
After the last changes in devdraw (cc3d97d52a72d7eaceb5b636bcdf81c3e19f7a2e - 04da0159764152b99b7dd0f33ace7d97ae7c2aa1) windows in X11 are not redrawn on resize events. For instance, when you maximize/resize an acme or sam window, the window stays blank until the mouse is moved over.

**Comment by rsc** [comment]
Thanks for the report. I think I've fixed it now. Let me know if not.

**Comment by aksr** [comment]
This is not fixed yet.  

For example, you can't see the text you're entering (after resizing).

Btw, if the initial size is wrong, it's impossible to "maximize" it or get it to be fullscreen on a tiling window manager, for example—especially visible if there is no other windows and initial size is wrong—and very often, initial size *is* wrong (*this is a very old bug*).

**Comment by jroimartin** [comment]
Thanks for the quick response. However, it does not seem to work on my side.

Now the behavior is the following:
- **Resize**: the window draws the old content in the top left position without readjusting the layout to the new size. Also, any further update in the contents of the window is not redrawn until the window is resized again (e.g. text changes, text cursor, etc).
- **Maximize before any resize**: blank screen.
- **Maximize after resizing the window at least once**: same as "Resize".
- **Before any resize**: window contents are updated properly (e.g. text changes, text cursor, etc).
